### ISSUE TITLE
i cant view the index page

### ISSUE THREAD

**Issue by emazzu** [m-inan/react-native-music-app#15]
how are you, 
i did npm install and npm start, but only watch to reload the app press "r" and to open developer menu press "d"

i hace the phone connected by USB, but nothing.

What can be happend ???

**Comment by m-inan** [comment]
Hi @emazzu, the commands you are running are only for running javascript servers. You have to enter another command to run it on Emulator or Real devices.

### IOS
```npx react-native run-ios```

### Android
```npx react-native run-android```

For more detailed information, you can check the react-native [Running On Device](https://reactnative.dev/docs/running-on-device) page.

**Comment by emazzu** [comment]
Thank you so much for the info.

**Comment by emazzu** [comment]
hi, one question more.
when I run this command npx react-native run-android, and I connect the device by USB, the app should show on device ???
Regards,

**Comment by m-inan** [comment]
@emazzu If the necessary tools are installed and you have given the necessary permissions on your device, the application will open after the code is compiled.
You can test that the device is connected with this command.
```
adb device
```
