### ISSUE TITLE
[Requested] - Improve redux 

### ISSUE THREAD

**Issue by kristoff2016** [m-inan/react-native-music-app#3]
Hello @TPMinan , 

Thank you for your great sharing the app. I tried to follow your code but it is difficult to understand could you help improve add comment to each func redux does?

Thank you

**Comment by m-inan** [comment]
Hi, @kristoff2016 
Instead of adding a comment line, I can publish a guide for it. What exactly is the problem? Is your place in the playlist or in playback?

**Comment by kristoff2016** [comment]
Hello @TPMinan  what I meant if your code is readbale then I could easier to understand and implement by own way  just follow yours.
