### ISSUE TITLE
react-native run android

### ISSUE THREAD

**Issue by phoens** [m-inan/react-native-music-app#4]
when I run the above command  after "Set Up Instructions"
I am getting a lot of errors. Can you please provide exact steps to get an apk into mobile phone.

like,  "yarn start && react-native run-android" for general projects.

Thanks

**Comment by m-inan** [comment]
@mohankoppuravuri  I understand. I prepare separate manuals and update them.

**Comment by m-inan** [comment]
@mohankoppuravuri You can start the application by following these steps for now. You can see the changes here. https://github.com/TPMinan/react-native-music-app/commit/b2bad318d972d8e91e3a8f452822e5516c2d86c9
