### ISSUE TITLE
Can't run using Gradle 6.0

### ISSUE THREAD

**Issue by tanasecosminromeo** [m-inan/react-native-music-app#5]
Hi there, I cannot run the project on android, looks to be an issue with deprecated features

`romeo@Cosmin-Romeos-MacBook-Pro musix % npx react-native run-android                   
info JS server already running.
info Building and installing the app on the device (cd android && ./gradlew app:installDebug)...

> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Task :react-native-fs:compileDebugJavaWithJavac FAILED
/Users/romeo/Work/musix/node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSManager.java:11: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/romeo/Work/musix/node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSManager.java:624: error: cannot find symbol
  private void sendEvent(ReactContext reactContext, String eventName, @Nullable WritableMap params) {
                                                                       ^
  symbol:   class Nullable
  location: class RNFSManager
Note: /Users/romeo/Work/musix/node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fs:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
42 actionable tasks: 1 executed, 41 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: ./gradlew app:installDebug. Run CLI with --verbose flag for more details.`

Any tips?

**Comment by m-inan** [comment]
Hi, I'm aware of the problem. Adaptation problem for RN-0.60 and higher. An update of 0.60 and higher would be very painful. So I can only offer you a temporary way of doing things.

### Step 1: 
Remove some code from the RNFSManager.java 
> /node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSManager.java:11

```java
...
import android.os.StatFs;
import android.provider.MediaStore;
import android.support.annotation.Nullable; // remove line 11
import android.util.Base64;
import android.util.SparseArray;
```
> /node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSManager.java:624
> Remove annotation `@Nullable`
```java
private void sendEvent(ReactContext reactContext, String eventName, @Nullable WritableMap params) {
  reactContext
  .getJSModule(RCTNativeAppEventEmitter.class)
  .emit(eventName, params);
}
```
### Step 2: 
> /android/gradle.properties
> Remove Android X Support
```gradle
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true

android.useAndroidX=true // remove line
android.enableJetifier=true
MYAPP_RELEASE_STORE_FILE=my-upload-key.keystore
MYAPP_RELEASE_KEY_ALIAS=my-key-alias
MYAPP_RELEASE_STORE_PASSWORD=musicapp
```
### Step 3: 
finally you can start it after getting build with `jetifier`
```shell
npx jetify && react-native run-android
```
