### ISSUE TITLE
i got error while run project 'Import dotenv as default is not supported'

### ISSUE THREAD

**Issue by sunilmanipara** [m-inan/react-native-music-app#7]
The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false

Body:
{"type":"TransformError","lineNumber":0,"errors":[{"description":"src\\constants\\Api.js: C:\\Users\\ecs\\Downloads\\music-app-master\\node_modules\\react-native\\scripts\\src\\constants\\Api.js: Import dotenv as default is not supported.\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 1 | \u001b[39m\u001b[36mimport\u001b[39m \u001b[33mSERVICE_URLS\u001b[39m from \u001b[32m'react-native-dotenv'\u001b[39m\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m   | \u001b[39m       \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 2 | \u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 3 | \u001b[39m\u001b[36mexport\u001b[39m \u001b[36mdefault\u001b[39m \u001b[33mSERVICE_URLS\u001b[39m\u001b[0m","lineNumber":0}],"name":"SyntaxError","message":"src\\constants\\Api.js: C:\\Users\\ecs\\Downloads\\music-app-master\\node_modules\\react-native\\scripts\\src\\constants\\Api.js: Import dotenv as default is not supported.\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 1 | \u001b[39m\u001b[36mimport\u001b[39m \u001b[33mSERVICE_URLS\u001b[39m from \u001b[32m'react-native-dotenv'\u001b[39m\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m   | \u001b[39m       \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 2 | \u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 3 | \u001b[39m\u001b[36mexport\u001b[39m \u001b[36mdefault\u001b[39m \u001b[33mSERVICE_URLS\u001b[39m\u001b[0m","stack":"SyntaxError: C:\\Users\\ecs\\Downloads\\music-app-master\\node_modules\\react-native\\scripts\\src\\constants\\Api.js: Import dotenv as default is not supported.\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 1 | \u001b[39m\u001b[36mimport\u001b[39m \u001b[33mSERVICE_URLS\u001b[39m from \u001b[32m'react-native-dotenv'\u001b[39m\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m   | \u001b[39m       \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 2 | \u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 3 | \u001b[39m\u001b[36mexport\u001b[39m \u001b[36mdefault\u001b[39m \u001b[33mSERVICE_URLS\u001b[39m\u001b[0m\n    at File.buildCodeFrameError (C:\\Users\\ecs\\Downloads\\music-app-master\\node_modules\\@babel\\core\\lib\\transformation\\file\\file.js:261:12)\n    at NodePath.buildCodeFrameError (C:\\Users\\ecs\\Downloads\\music-app-master\\node_modules\\@babel\\traverse\\lib\\path\\index.js:157:21)\n    at C:\\Users\\ecs\\Downloads\\music-app-master\\node_modules\\babel-plugin-dotenv\\index.js:29:57\n    at Array.forEach (<anonymous>)\n    at PluginPass.ImportDeclaration (C:\\Users\\ecs\\Downloads\\music-app-master\\node_modules\\babel-plugin-dotenv\\index.js:27:40)\n    at newFn (C:\\Users\\ecs\\Downloads\\music-app-master\\node_modules\\@babel\\traverse\\lib\\visitors.js:193:21)\n    at NodePath._call (C:\\Users\\ecs\\Downloads\\music-app-master\\node_modules\\@babel\\traverse\\lib\\path\\context.js:53:20)\n    at NodePath.call (C:\\Users\\ecs\\Downloads\\music-app-master\\node_modules\\@babel\\traverse\\lib\\path\\context.js:40:17)\n    at NodePath.visit (C:\\Users\\ecs\\Downloads\\music-app-master\\node_modules\\@babel\\traverse\\lib\\path\\context.js:88:12)"}
processBundleResult
    BundleDownloader.java:296
access$200
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:174
execute
    RealCall.java:206
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1167
run
    ThreadPoolExecutor.java:641
run
    Thread.java:764

- please help me if have any solutions, thanks

**Comment by m-inan** [comment]
Unfortunately, the package 'react-native-dot` is not up to date. Instead, you can write 'fixed' data into the file.

In the order of the steps you need to follow.

Step 1.
```shell
npm uninstall react-native-dotenv
```

Step 2.
```javascript
// src/constants/Api.js

- import { SERVICE_URL } from 'react-native-dotenv'

export default {
  SERVICE_URL
}
```
```javascript
// src/constants/Api.js

+ const SERVICE_URL = "http://localhost:3000" // localhost or local ip address

export default {
  SERVICE_URL
}
```
